apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: app
        image: ci-cd-docker-demo:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-service
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080

